server:
  port: 8761
  application:
    name: service-management

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    leaseRenewalIntervalInSeconds: 10