spring:
  application:
    name: service-management
  boot:
    admin:
      context-path: /admin

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
  instance:
    leaseRenewalIntervalInSeconds: 10