server:
  port: 8081

spring:
  application:
    name: employment-management

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"